[ci]
runtime = "nix"
runner = "atlas-nix-trusted"
with_docs = true
step_runners = { cargo-clippy = "codeberg-small", cargo-doc = "codeberg-small", cargo-fmt = "codeberg-tiny", cargo-package = "codeberg-medium", cargo-test = "codeberg-medium", nix-check = "atlas-nix-trusted", quality-tools = "codeberg-small" }
platform = "forgejo"
publish_crates = true
provider = "actions"

[ci.pages]
repo = "caniko/dns-manager"
canonical_domain = "dns-manager.tartanoglu.com"
