[ci]
runtime = "nix"
runner = "ubuntu-24.04"
with_docs = true
platform = "github"
publish_crates = true
provider = "actions"

[ci.pages]
repo = "caniko/dns-manager"
canonical_domain = "dns-manager.tartanoglu.com"
