[book]
title = "dns-manager Documentation"
authors = ["caniko"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/dns-manager/"
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/caniko/dns-manager"
